# Installed to /etc/fail2ban/filter.d/wp-honeypot-login.conf
# Matches failed-login JSON lines written by mu-plugins/honeypot-logger.php.
[Definition]
failregex = ^.*"type":\s*"login_failed".*"ip":\s*"<HOST>".*$
ignoreregex =
